use crate::models::IdentityProfile;
use std::fs;

pub fn generate_html_report(profile: &IdentityProfile, output_path: &str) {
    let mut nodes_json = String::from("[");
    let mut edges_json = String::from("[");

    nodes_json.push_str(&format!("{{id:'{}',label:'{}',group:'{:?}',title:'Root: {}'}},", js_escape(&profile.root_entity.value), js_escape(&profile.root_entity.value), profile.root_entity.entity_type, js_escape(&profile.root_entity.value)));
    for (value, node) in &profile.associated_nodes {
        nodes_json.push_str(&format!("{{id:'{}',label:'{}',group:'{:?}',title:'Type: {:?}'}},", js_escape(value), js_escape(value), node.entity_type, node.entity_type));
    }
    for link in &profile.active_links {
        edges_json.push_str(&format!("{{from:'{}',to:'{}',label:'{}',title:'source={} | class={:?} | year={} | weight={}'}},", js_escape(&link.source_node_value), js_escape(&link.target_node_value), js_escape(&link.metadata.source_id), js_escape(&link.metadata.source_id), link.metadata.class, link.metadata.data_actual_year, link.weight_modifier));
    }
    if nodes_json.ends_with(',') { nodes_json.pop(); }
    if edges_json.ends_with(',') { edges_json.pop(); }
    nodes_json.push(']');
    edges_json.push(']');

    let html = format!(r#"<!DOCTYPE html>
<html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>X-GEN OSINT Dashboard</title><script src="https://unpkg.com/vis-network/standalone/umd/vis-network.min.js"></script><style>
:root{{--bg:#0b1020;--panel:#111827;--text:#e5e7eb;--muted:#9ca3af;--line:rgba(148,163,184,.25);--green:#34d399;--yellow:#fbbf24;--red:#fb7185}}
*{{box-sizing:border-box}} body{{margin:0;font-family:Segoe UI,Arial,sans-serif;background:var(--bg);color:var(--text);overflow:hidden}} .app{{display:grid;grid-template-columns:460px 1fr;height:100vh;width:100vw}} .sidebar{{overflow:auto;padding:16px;border-right:1px solid var(--line);background:linear-gradient(180deg,#0f172a,#111827)}} h1{{font-size:18px;margin:0 0 4px}} small{{color:var(--muted)}} .cards{{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:14px 0}} .card,.row{{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:12px}} .card h2{{margin:0 0 8px;font-size:12px;color:var(--muted)}} .metric{{font-size:24px;font-weight:800}} .section{{margin-top:12px}} .section-title{{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.08em;margin-bottom:8px}} .list{{display:grid;gap:8px}} .row strong{{display:block;font-size:13px;margin-bottom:4px}} .row span,.row code{{color:var(--muted);font-size:12px;overflow-wrap:anywhere}} .ok{{color:var(--green)}} .warn{{color:var(--yellow)}} .bad{{color:var(--red)}} .tag{{display:inline-block;margin:2px 4px 2px 0;padding:2px 6px;border-radius:999px;background:rgba(148,163,184,.14);border:1px solid rgba(148,163,184,.22);font-size:11px;color:var(--muted)}} .badtag{{color:var(--red);border-color:rgba(251,113,133,.35);background:rgba(251,113,133,.12)}} #graph{{width:100%;height:100vh;background:radial-gradient(circle at top left,rgba(56,189,248,.12),transparent 35%),#090e1a}} .info-panel{{position:absolute;top:14px;left:14px;max-width:460px;background:rgba(2,6,23,.88);padding:14px;border-radius:14px;border:1px solid var(--line);display:none}} .graph-wrap{{position:relative;min-width:0}} button{{background:#2563eb;color:white;border:0;padding:8px 12px;border-radius:10px;margin-top:10px;cursor:pointer}} .mono{{font-family:ui-monospace,Consolas,monospace}} @media(max-width:980px){{body{{overflow:auto}}.app{{grid-template-columns:1fr;height:auto}}#graph{{height:70vh}}}}
</style></head><body><div class="app"><aside class="sidebar"><h1>X-GEN OSINT Dashboard</h1><small>Graph + runtime reports</small><div class="cards"><div class="card"><h2>Узлы</h2><div class="metric" id="mNodes">—</div></div><div class="card"><h2>Связи</h2><div class="metric" id="mEdges">—</div></div><div class="card"><h2>Confidence</h2><div class="metric" id="mConfidence">—</div></div><div class="card"><h2>Conflicts</h2><div class="metric" id="mConflicts">—</div></div></div>
<div class="section"><div class="section-title">Master Verdict</div><div class="list" id="masterBox"><div class="row"><span>Загрузка master_report.json…</span></div></div></div>
<div class="section"><div class="section-title">Phone Intel</div><div class="list" id="phoneBox"><div class="row"><span>Загрузка phone_intel_report.json…</span></div></div></div>
<div class="section"><div class="section-title">Autopilot</div><div class="list" id="autopilotBox"><div class="row"><span>Загрузка autopilot_report.json…</span></div></div></div>
<div class="section"><div class="section-title">Email / Domain</div><div class="list" id="emailBox"><div class="row"><span>Загрузка email_domain_report.json…</span></div></div></div>
<div class="section"><div class="section-title">Discovery / Noise</div><div class="list" id="discoveryBox"><div class="row"><span>Загрузка discovery_report.json…</span></div></div></div>
<div class="section"><div class="section-title">Public Search / Noise</div><div class="list" id="searchBox"><div class="row"><span>Загрузка public_search_report.json…</span></div></div></div>
<div class="section"><div class="section-title">Confidence Guardrails</div><div class="list" id="confidenceBox"><div class="row"><span>Загрузка confidence_report.json…</span></div></div></div>
<div class="section"><div class="section-title">Conflicts</div><div class="list" id="conflictBox"><div class="row"><span>Загрузка conflict_report.json…</span></div></div></div>
</aside><main class="graph-wrap"><div id="graph"></div><div id="info" class="info-panel"></div></main></div>
<script>
const nodes=new vis.DataSet({nodes_json}); const edges=new vis.DataSet({edges_json}); document.getElementById('mNodes').textContent=nodes.length; document.getElementById('mEdges').textContent=edges.length;
const network=new vis.Network(document.getElementById('graph'),{{nodes,edges}},{{nodes:{{shape:'dot',size:18,font:{{color:'#e5e7eb'}},borderWidth:2}},edges:{{color:{{color:'rgba(148,163,184,.5)'}},font:{{color:'#9ca3af',size:10}},smooth:true}},physics:{{stabilization:true,barnesHut:{{gravitationalConstant:-26000,springLength:130}}}},groups:{{Nickname:{{color:'#f59e0b'}},Username:{{color:'#f59e0b'}},Email:{{color:'#38bdf8'}},Phone:{{color:'#34d399'}},FullName:{{color:'#e879f9'}},Url:{{color:'#a78bfa'}},Domain:{{color:'#60a5fa'}},Country:{{color:'#facc15'}},DateOfBirth:{{color:'#fb7185'}},DataSource:{{color:'#94a3b8'}}}}}});
network.on('click',p=>{{if(!p.nodes.length)return;const id=p.nodes[0];const safe=String(id).replaceAll('\\','\\\\').replaceAll('`','\\`').replaceAll("'","\\'");const box=document.getElementById('info');box.style.display='block';box.innerHTML=`<strong>Узел:</strong><br><span class="mono">${{escapeHtml(id)}}</span><br><button onclick="expandNode('${{safe}}')">🔍 Искать связи</button>`;}});
function expandNode(nodeId){{fetch('/expand',{{method:'POST',headers:{{'Content-Type':'application/json'}},body:JSON.stringify({{target:nodeId}})}}).then(r=>{{if(r.ok)alert('Запрос отправлен. Обнови страницу после завершения.')}})}}
async function loadJson(path){{try{{const r=await fetch(path,{{cache:'no-store'}});if(!r.ok)throw new Error(r.status);return await r.json();}}catch(e){{return null;}}}}
function escapeHtml(v){{return String(v??'').replace(/[&<>'"]/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}}[c]));}}
function n(v){{return Number.isFinite(Number(v))?Number(v).toLocaleString('ru-RU'):'—';}}
function row(t,b,cls=''){{return `<div class="row"><strong class="${{cls}}">${{escapeHtml(t)}}</strong><span>${{b}}</span></div>`;}}
function tags(values,bad=false){{return (values||[]).map(v=>`<span class="tag ${{bad?'badtag':''}}">${{escapeHtml(v)}}</span>`).join('')||'<span class="tag">none</span>';}}
function statusCls(status){{const s=String(status||'').toLowerCase();if(s==='matched'||s==='strongcorrelations'||s==='actionablecorrelations'||s==='strong'||s==='probable'||s==='high'||s==='veryhigh')return 'ok';if(s==='ratelimited'||s==='error'||s==='providerblocked'||s==='low')return 'bad';if(s==='skipped'||s==='emptyresult'||s==='nopublichits'||s==='publictraceonly'||s==='weaksignals'||s==='weak'||s==='possible'||s==='medium')return 'warn';return '';}}
Promise.all(['master_report.json','phone_intel_report.json','autopilot_report.json','email_domain_report.json','discovery_report.json','public_search_report.json','confidence_report.json','conflict_report.json'].map(loadJson)).then(([master,phone,auto,email,discovery,search,confidence,conflicts])=>{{renderMaster(master);renderPhone(phone);renderAutopilot(auto);renderEmail(email);renderDiscovery(discovery);renderSearch(search);renderConfidence(confidence);renderConflicts(conflicts);}});
function renderMaster(r){{const b=document.getElementById('masterBox');if(!r){{b.innerHTML=row('Нет данных','master_report.json не найден','warn');return;}}const v=r.verdict||{{}},s=r.summary||{{}};b.innerHTML=row(v.status||'unknown',`confidence=${{v.confidence_adjusted??'—'}} | high_risk=${{v.high_risk??false}} | missing=${{n((r.missing_reports||[]).length)}}`,v.high_risk?'bad':'warn');b.innerHTML+=row('Pipeline',`profile=${{escapeHtml(s.run_profile||'—')}} | phone=${{n(s.phone_checked)}} | phone_public=${{n(s.phone_public_mentions)}} | phone_api_errors=${{n(s.phone_api_errors)}} | auto_new=${{n(s.autopilot_new_nodes)}}`);if((v.reasons||[]).length)b.innerHTML+=row('Reasons',tags(v.reasons,true));}}
function renderPhone(r){{const b=document.getElementById('phoneBox');if(!r){{b.innerHTML=row('Нет данных','phone_intel_report.json не найден','warn');return;}}const s=r.stats||{{}};const q=r.source_quality||{{}};b.innerHTML=row('Phone summary',`checked=${{n(s.phones_checked)}} | valid=${{n(s.valid_shape)}} | carrier=${{n(s.carrier_guesses)}} | dossiers=${{n(s.final_dossiers)}} | actionable=${{n(s.actionable_dossiers)}} | public_mentions=${{n(s.public_mentions)}} | correlations=${{n(s.correlation_summaries)}} | strong=${{n(s.strong_correlations)}} | probable=${{n(s.probable_correlations)}} | quality=${{n(s.source_quality_scores)}} | high+=${{n(s.high_quality_phone_sources)}} | risky=${{n(s.risky_phone_sources)}} | api_errors=${{n(s.api_errors)}}`,s.actionable_dossiers||s.high_quality_phone_sources?'ok':(s.api_errors||s.risky_phone_sources?'warn':''));
if((r.final_dossiers||[]).length){{b.innerHTML+=row('Final dossiers','итог по каждому номеру: verdict, confidence, связи и следующие шаги','');for(const d of (r.final_dossiers||[]).slice(0,5)){{const cls=statusCls(d.verdict);b.innerHTML+=row(`${{d.phone_value||d.normalized_e164||d.raw_input}} / ${{d.verdict||'unknown'}}`,`confidence=${{n(d.confidence)}} | valid=${{d.valid_shape}} | country=${{escapeHtml(d.country_guess||'—')}} | carrier=${{escapeHtml(d.carrier_operator_guess||'—')}}/${{d.carrier_confidence??'—'}}<br>public=${{n(d.public_mentions)}} | signals=${{n(d.extracted_signals)}} | strong=${{n(d.strong_correlations)}} | probable=${{n(d.probable_correlations)}} | possible=${{n(d.possible_correlations)}} | weak=${{n(d.weak_correlations)}}<br>years=${{tags(d.year_hints||[])}}`,cls);if((d.top_correlations||[]).length){{for(const c of (d.top_correlations||[]).slice(0,4)){{b.innerHTML+=row(`↳ ${{c.entity_type}} / ${{c.level}} / ${{c.confidence}}%`,`value=<code>${{escapeHtml(c.value)}}</code><br>mentions=${{n(c.mentions)}} | sources=${{n(c.independent_sources)}} | urls=${{n(c.urls_count)}} | years=${{tags(c.year_hints||[])}}<br>source_ids=${{tags(c.source_ids||[])}}`,statusCls(c.level));}}}}if((d.next_steps||[]).length)b.innerHTML+=row('Next steps',tags(d.next_steps,false));if((d.cautions||[]).length)b.innerHTML+=row('Cautions',tags(d.cautions,true),'warn');}}}}
if((q.scores||[]).length){{b.innerHTML+=row('Source quality',`scores=${{n(q.scores.length)}} | high_or_better=${{n(q.high_or_better)}} | medium_or_better=${{n(q.medium_or_better)}} | low=${{n(q.low_quality)}} | risky=${{n(q.risky_sources)}}`,q.high_or_better?'ok':(q.risky_sources?'warn':''));for(const src of (q.scores||[]).slice(0,8)){{const cls=statusCls(src.quality_level);const url=src.url?`<br>url=<code>${{escapeHtml(src.url)}}</code>`:'';b.innerHTML+=row(`${{src.source_id}} / ${{src.quality_level}} / ${{src.quality_score}}%`,`phone=<code>${{escapeHtml(src.phone_value)}}</code>${{url}}<br>exact=${{src.exact_phone_match}} | context_chars=${{n(src.context_chars)}} | linked=${{n(src.linked_signal_count)}} | correlations=${{n(src.correlation_count)}} | years=${{tags(src.year_hints||[])}}<br>provider=${{escapeHtml(src.provider_status||'—')}} | hits=${{n(src.provider_hits)}} | errors=${{n(src.provider_errors)}} | rate_limited=${{n(src.provider_rate_limited)}}<br>strengths=${{tags(src.strengths||[])}}<br>risk=${{tags(src.risk_flags||[],true)}}<br>reasons=${{tags(src.reasons||[])}}`,cls);}}}}
for(const p of (r.phones||[]).slice(0,4)){{b.innerHTML+=row(p.e164||p.digits||p.raw,`raw=<code>${{escapeHtml(p.raw)}}</code><br>country=${{escapeHtml(p.country_guess||'—')}} | valid=${{p.valid_shape}}<br>notes=${{tags(p.notes||[])}}`,p.valid_shape?'ok':'warn');}}for(const g of (r.carrier_guesses||[]).slice(0,4)){{b.innerHTML+=row(`Carrier guess ${{g.confidence}}%`,`country=${{escapeHtml(g.country)}} | operator=${{escapeHtml(g.operator||'unknown')}} | type=${{escapeHtml(g.number_type)}}<br>${{escapeHtml(g.reason)}}`,'warn');}}if((r.provider_summaries||[]).length){{b.innerHTML+=row('Providers','сводка по источникам phone-проверки','');for(const p of (r.provider_summaries||[]).slice(0,8)){{b.innerHTML+=row(`${{p.provider_id}} / ${{p.status||'unknown'}}`,`enabled=${{p.enabled}} | terms=${{n(p.terms_attempted)}} | hits=${{n(p.hits)}} | empty=${{n(p.empty_results)}} | rate_limited=${{n(p.rate_limited)}} | errors=${{n(p.errors)}}${{p.last_error?'<br>last_error=<code>'+escapeHtml(p.last_error)+'</code>':''}}`,statusCls(p.status));}}}}if((r.traces||[]).length){{b.innerHTML+=row('Provider trace','последние проверки provider + term','');for(const t of (r.traces||[]).slice(0,12)){{const link=t.url?`<br>url=<code>${{escapeHtml(t.url)}}</code>`:'';const msg=t.message?`<br>msg=<code>${{escapeHtml(t.message)}}</code>`:'';b.innerHTML+=row(`${{t.provider_id}} / ${{t.status}}`,`term=<code>${{escapeHtml(t.term||'—')}}</code> | hits=${{n(t.hits)}}${{link}}${{msg}}`,statusCls(t.status));}}}}for(const m of (r.public_mentions||[]).slice(0,6)){{const link=m.url?`<br>url=<code>${{escapeHtml(m.url)}}</code>`:'';b.innerHTML+=row(`${{m.source_id}} / ${{m.confidence}}%`,`value=<code>${{escapeHtml(m.value)}}</code>${{link}}<br>${{escapeHtml(m.context_snippet||m.note||'')}}`,'ok');}}}}
function renderAutopilot(r){{const b=document.getElementById('autopilotBox');if(!r){{b.innerHTML=row('Нет данных','autopilot_report.json не найден','warn');return;}}const phoneNew=(r.cycles||[]).reduce((s,c)=>s+Number(c.new_phone_intel_nodes||0),0);b.innerHTML=row('Сводка',`cycles=${{n(r.cycles?.length)}} | initial=${{n(r.initial_seed_count)}} | final=${{n(r.final_seed_count)}} | new=${{n(r.total_new_nodes)}} | phone_new=${{n(phoneNew)}}`);for(const c of (r.cycles||[]).slice(0,4))b.innerHTML+=row(`Cycle ${{c.cycle}}`,`input=${{n(c.input_seed_count)}} | phone=${{n(c.new_phone_intel_nodes)}} | email=${{n(c.new_email_domain_nodes)}} | discovery=${{n(c.new_discovery_nodes)}} | search=${{n(c.new_public_search_nodes)}} | total=${{n(c.total_seed_count_after_cycle)}}`);}}
function renderEmail(r){{const b=document.getElementById('emailBox');if(!r){{b.innerHTML=row('Нет данных','email_domain_report.json не найден','warn');return;}}const s=r.stats||{{}};b.innerHTML=row('Email/domain',`emails=${{n(s.emails_checked)}} | valid=${{n(s.valid_emails)}} | domains=${{n(s.domains_checked)}} | candidates=${{n(s.username_candidates)}} | suspicious=${{n(s.suspicious_domains)}}`);for(const d of (r.dns_summaries||[]).slice(0,5))b.innerHTML+=row(d.domain||'domain',`provider=${{escapeHtml(d.provider_class||'unknown')}} | MX=${{d.has_mx?'yes':'no'}} | TXT=${{d.has_txt?'yes':'no'}}<br>risk=${{tags(d.risk_flags||[],true)}}`,(d.risk_flags||[]).length?'warn':'ok');}}
function renderDiscovery(r){{const b=document.getElementById('discoveryBox');if(!r){{b.innerHTML=row('Нет данных','discovery_report.json не найден','warn');return;}}const s=r.stats||{{}};b.innerHTML=row('Discovery',`tasks=${{n(s.tasks_planned)}} | fetched=${{n(s.tasks_fetched)}} | findings=${{n(s.findings_count)}} | blocked=${{n(s.blocked_by_noise_rules)}} | downranked=${{n(s.downranked_by_noise_rules)}} | errors=${{n(s.fetch_errors)}}`);}}
function renderSearch(r){{const b=document.getElementById('searchBox');if(!r){{b.innerHTML=row('Нет данных','public_search_report.json не найден','warn');return;}}const s=r.stats||{{}};b.innerHTML=row('Public search',`tasks=${{n(s.tasks_planned)}} | executed=${{n(s.tasks_executed)}} | findings=${{n(s.findings_count)}} | blocked=${{n(s.blocked_by_noise_rules)}} | downranked=${{n(s.downranked_by_noise_rules)}}`);}}
function renderConfidence(r){{const b=document.getElementById('confidenceBox');if(!r){{b.innerHTML=row('Нет данных','confidence_report.json не найден','warn');return;}}document.getElementById('mConfidence').textContent=`${{r.adjusted_score??'—'}}%`;b.innerHTML=row('Score',`original=${{r.original_score}} | adjusted=${{r.adjusted_score}} | sources=${{n(r.unique_sources)}} | classes=${{n(r.unique_source_classes)}}`);}}
function renderConflicts(r){{const b=document.getElementById('conflictBox');if(!r){{b.innerHTML=row('Нет данных','conflict_report.json не найден','warn');return;}}const f=r.findings||[];document.getElementById('mConflicts').textContent=f.length;b.innerHTML=row('Conflict Engine',`findings=${{n(f.length)}} | severity=${{n(r.severity_score)}} | high_risk=${{r.high_risk??false}}`,f.length?'bad':'ok');for(const x of f.slice(0,4))b.innerHTML+=row(`${{x.severity||'Conflict'}} / ${{x.kind||''}}`,escapeHtml(x.message||x.entity_value||''));}}
</script></body></html>"#, nodes_json = nodes_json, edges_json = edges_json);
    fs::write(output_path, html).expect("Не удалось записать HTML-отчёт");
}

fn js_escape(value: &str) -> String {
    value.replace('\\', "\\\\").replace('\'', "\\'").replace('\n', " ").replace('\r', " ")
}
